/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDER_H_RPCGEN
#define _ADDER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct inputs {
	float num1;
	float num2;
};
typedef struct inputs inputs;
#ifdef __cplusplus
extern "C" bool_t xdr_inputs(XDR *, inputs*);
#elif __STDC__
extern  bool_t xdr_inputs(XDR *, inputs*);
#else /* Old Style C */
bool_t xdr_inputs();
#endif /* Old Style C */


#define ADDER_PROG ((rpc_uint)0x2fffffff)
#define ADDER_VER ((rpc_uint)1)

#ifdef __cplusplus
#define ADD ((rpc_uint)1)
extern "C" float * add_1(inputs *, CLIENT *);
extern "C" float * add_1_svc(inputs *, struct svc_req *);

#elif __STDC__
#define ADD ((rpc_uint)1)
extern  float * add_1(inputs *, CLIENT *);
extern  float * add_1_svc(inputs *, struct svc_req *);

#else /* Old Style C */
#define ADD ((rpc_uint)1)
extern  float * add_1();
extern  float * add_1_svc();
#endif /* Old Style C */

#endif /* !_ADDER_H_RPCGEN */
