/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "adder.h"

float *
add_1_svc(inputs *argp, struct svc_req *rqstp)
{

	static float  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
