/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "adder.h"

bool_t
xdr_inputs(XDR *xdrs, inputs *objp)
{

	if (!xdr_float(xdrs, &objp->num1))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->num2))
		return (FALSE);
	return (TRUE);
}
